
GET http://localhost:3100/v1/f/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYTM5Y2E2NC02MDZhLTRmNDItOWMyMS00MWY3MGJmYjA4MjQiLCJuYW1lIjoiRG9kb2tqcjEyMzQiLCJlbWFpbCI6ImZmaWtyaTY0QGdtYWlsLmNvbSIsImltYWdlX3Byb2ZpbGUiOiJodHRwOi8vbG9jYWxob3N0OjMxMDAvcGhvdG9Qcm9maWxlLzE3MjUyMDE4OTYwNDRlODE5Njg0ZTE2NzViODUwMWE3ZjE4NTdhYjI0YWFiYi5naWYiLCJpYXQiOjE3MjUyNjAyNTksImV4cCI6MTcyNTI2MjA1OX0.WmcxvQU0M5ZUlUA3k3MKW_NQNJhAE-F8GEmC5HgcK9U
###
# Register
POST http://localhost:3100/v1/f/users
Content-Type: application/json

{
    "name": "Dodokjr1234",
    "email": "ffikri64@gmail.com",
    "password": "Ruwet133#",
    "conformPassword": "Ruwet133#",
    "pin": "12345"
}

###
# Login
POST http://localhost:3100/v1/f/login
Content-Type: application/json

{
    "name": "dodokjr1234",
    "password": "Seruni133#",
    "pin": "12345"
}

###
# Get UserProfile
GET http://localhost:3100/v1/f/users/dodokjr1234
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYTM5Y2E2NC02MDZhLTRmNDItOWMyMS00MWY3MGJmYjA4MjQiLCJuYW1lIjoiRG9kb2tqcjEyMzQiLCJlbWFpbCI6ImZmaWtyaTY0QGdtYWlsLmNvbSIsImltYWdlX3Byb2ZpbGUiOiJodHRwOi8vbG9jYWxob3N0OjMxMDAvcGhvdG9Qcm9maWxlLzE3MjUxOTMwMjgwOTI5MDBkYmRjNTM3ZWZhZjUxMDVjMzJmYWM0Yzc0MTUwYi5qcGciLCJpYXQiOjE3MjUxOTQ5ODcsImV4cCI6MTcyNTE5Njc4N30.bEzz_E3_i3ZsHCXIBRClRMEj4GZ9xgDrxP9balW_p7U

###
# getResetPassword
POST http://localhost:3100/v1/f/forgotpasword
Content-Type: application/json

{
    "name": "dodokjr1234"
}
###
# resetPassword
POST http://localhost:3100/v1/f/forgotpasword/ffikri64@gmail.com
Content-Type: application/json

{
    "password": "Seruni133#",
    "conformPassword": "Seruni133#"
}
###
# Auto Reset Password
GET http://localhost:3100/v1/f/a/forgotpassword 
Content-Type: application/json

{
    "email" : "ffikri64@gmail.com"
}

###
DELETE http://localhost:3100/logout